#!/bin/zsh

# Display username always
SPACESHIP_USER_SHOW=always
# Show hostname
SPACESHIP_HOST_SHOW=always
# Do not truncate path in repos
SPACESHIP_DIR_TRUNC_REPO=false
# Username color
SPACESHIP_USER_COLOR=green

SPACESHIP_PROMPT_ADD_NEWLINE=false

SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  bun           # Bun section
  deno          # Deno section
  python        # Python section
  rust          # Rust section
  java          # Java section
  docker        # Docker section
  exec_time     # Execution time
  async         # Async jobs indicator
  line_sep      # Line break
  battery       # Battery level and status
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
